CREATE FUNCTION SUM(value REAL) AS REAL;
CREATE FUNCTION MIN(value REAL) AS REAL;
CREATE FUNCTION MAX(value REAL) AS REAL;
CREATE FUNCTION AVG(value REAL) AS REAL;
CREATE FUNCTION COUNT(value REAL) AS REAL;

CREATE FUNCTION APPROX_COUNT_DISTINCT_ESTIMATE(value REAL) AS REAL;
CREATE FUNCTION unhex(value INT) AS INT;
CREATE FUNCTION concat(lhs CHAR, rhs CHAR) AS CHAR;
CREATE FUNCTION date(value CHAR) AS DATETIME;
CREATE FUNCTION pow(base REAL, exp REAL) AS REAL;
CREATE FUNCTION date_trunc(value REAL) AS REAL;
CREATE FUNCTION last(value REAL) AS REAL;
CREATE FUNCTION u256_to_decimal(value REAL) AS REAL;