CREATE FUNCTION SUM(value REAL) AS REAL;
CREATE FUNCTION MIN(value REAL) AS REAL;
CREATE FUNCTION MAX(value REAL) AS REAL;
CREATE FUNCTION AVG(value REAL) AS REAL;
CREATE FUNCTION COUNT(value REAL) AS REAL;