CREATE TYPE BOOLEAN ();
CREATE TYPE SMALLINT ();
CREATE TYPE INT ();
CREATE TYPE INTEGER ();
CREATE TYPE REAL (
    precision INTEGER
);
CREATE TYPE FLOAT ();
CREATE TYPE NUMERIC (
    precision INTEGER,
    scale INTEGER
);
CREATE TYPE DECIMAL (
    precision INTEGER,
    scale INTEGER
);
CREATE TYPE DOUBLE PRECISION ();