CREATE TABLE employees (
    id INTEGER,
    name TEXT,
    birthday REAL,
    salary REAL
);

CREATE TABLE managers (
    managerId INTEGER,
    employeeId INTEGER
);

CREATE FUNCTION SUM (summand REAL) AS INT;

CREATE DATABASE ALL_SCHEMA;
CREATE SCHEMA ALL_SCHEMA.SCHEMATA;

CREATE TABLE ALL_SCHEMA.SCHEMATA.`TABLE`(id int);